# Generated by Django 4.2.1 on 2023-05-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Fist_name',
            new_name='first_name',
        ),
    ]
